---
job: extension
config:
  name: "lora_name"
  process:
    - type: 'sd_trainer'
      training_folder: "/content/Lora"
      device: cuda:0
      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 100
        push_to_hub: false
      datasets:
        - folder_path: ""
          control_path: ""
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [ 1024 ]
      train:
        batch_size: 2
        steps: 3000
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw8bit"
        lr: 1e-4
        timestep_type: "weighted"
        dtype: bf16
      model:
        name_or_path: "black-forest-labs/FLUX.1-Kontext-dev"
        arch: "flux_kontext"
        quantize: true 
      sample:
        sampler: "flowmatch" 
        sample_every: 250
        width: 768
        height: 1152
        prompts:
          - ""
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 20
meta:
  name: "lora_name"
  version: '1.0'
